### ISSUE TITLE
On Windows 10, 64-Bit, use the X86 installer, not the X86-64

### ISSUE THREAD

**Issue by Asure** [DNA64/SuperHakchi#1]
The 64-bit version of Python 3.6.0 creates 0 byte files only.
No issues using the x86 version.

**Comment by DNA64** [comment]
Strange as I'm using the 64-bit version myself on Windows 7 64-Bit with no issues.

**Comment by Asure** [comment]
Closing the issue: I had older python version(s) installed, and removed them before doing the x86 only install. So this is not related to the x86/x64 version, but to having multiple installs.
