### ISSUE TITLE
The led blinking

### ISSUE THREAD

**Issue by AlbertoBortolato** [DNA64/SuperHakchi#2]
I follow the guide, but all I got is the snes blinking on startup

**Comment by DNA64** [comment]
I have no idea what you have done but I'm guessing you deviated from the guide in some way.
I will review the guide to try and see how you've come to this situation.

**Comment by Asure** [comment]
If you use a crappy USB cable, the snes will not get enough power to run. Did you try other USB cables?
You should still be able to get into FEL mode (hold reset, then power on, wait 3-4 seconds.) Does FEL mode work?

**Comment by DNA64** [comment]
Thank you, I forgot about that being an issue. @AlbertoBortolato are you using the original USB cable that came with the SNES? It can cause issues including the system led flashing.
