### ISSUE TITLE
Suspend Points

### ISSUE THREAD

**Issue by brycebelen** [DNA64/SuperHakchi#4]
With the custom kernel flashed onto my console it seems like the save state/Suspend Points no longer function. Attempting to save one after resetting from a game does nothing.

Not sure if this is a result of the hakchi custom kernel or something else I did while following the guide.

**Comment by BMoneyFlash** [comment]
I have the same issue - rewind / save states are broken. When you return to the menu and press the down arrow the system just freezes (music keeps playing, but you can't do anything except power off). Even when flashing back to the original kernel, rewind / save states stay broken. My guess is this is a result of the hakchi custom kernel. The NES Classic supported save states, but it didn't support rewinding. The SNES Classic probably works differently with regard to rewind / save states and they'll have to fix that in the custom kernel.

**Comment by DNA64** [comment]
My save states work just fine, I don't believe this has anything to do with the custom kernel as many people  including myself don't have this issue.

**Comment by DNA64** [comment]
Save States are located in "/var/lib/clover/profiles/0"
If you change this directory you won't see them. Please make a backup as soon as you have FTP access!
